---
- name: Uninstall Apache Tomcat 10 using Ansible
  hosts: webservers
  remote_user: ec2-user
  become: true
  vars:
    tomcat_install_directory: "/opt/tomcat10"

  tasks:
    - name: Stop Tomcat Service
      systemd:
        name: tomcat
        state: stopped
      ignore_errors: yes

    - name: Disable Tomcat Service
      systemd:
        name: tomcat
        enabled: no
      ignore_errors: yes

    - name: Remove Tomcat Service File
      file:
        path: /etc/systemd/system/tomcat.service
        state: absent
      notify: reload systemd

    - name: Remove Tomcat Installation Directory
      file:
        path: "{{ tomcat_install_directory }}"
        state: absent

    - name: Remove Tomcat User
      user:
        name: tomcat
        state: absent
      ignore_errors: yes

    - name: Remove Tomcat Group
      group:
        name: tomcat
        state: absent
      ignore_errors: yes

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes
