#!/bin/bash
sudo apt update
sudo hostnamectl set-hostname Maven
sudo apt install wget nano tree unzip git-all -y
sudo apt install java-11-openjdk-devel java-1.8.0-openjdk-devel -y
cd /opt
sudo wget https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.zip
sudo unzip apache-maven-3.9.4-bin.zip
sudo rm -rf apache-maven-3.9.4-bin.zip
sudo mv apache-maven-3.9.4/ maven
echo "# .bash_profile" > /home/ec2-user/.bash_profile
echo "export M2_HOME=/opt/maven" >> /home/ec2-user/.bash_profile
echo 'export PATH=$PATH:$M2_HOME/bin' >> /home/ec2-user/.bash_profile
echo "# Get the aliases and functions" >> /home/ec2-user/.bash_profile
echo "if [ -f ~/.bashrc ]; then" >> /home/ec2-user/.bash_profile
echo "        . ~/.bashrc" >> /home/ec2-user/.bash_profile
echo "fi " >> /home/ec2-user/.bash_profile
echo "# User specific environment and startup programs" >> /home/ec2-user/.bash_profile 
source /home/ec2-user/.bash_profile
